### ISSUE TITLE
Documentation: When should you pick Heimdall over the alternatives ?

### ISSUE THREAD

**Issue by rShetty** [gojektech/heimdall#14]

**Comment by sohamkamani** [comment]
Most other repos have an `FAQ` section at the end of the README for stuff like this. We can probably add it there?

**Comment by rShetty** [comment]
@sohamkamani A FAQ section would make more sense, I think

**Comment by rShetty** [comment]
@sohamkamani Do you want to work on this documentation for FAQ's ?

**Comment by sohamkamani** [comment]
Yes I can take it up @rShetty

**Comment by rShetty** [comment]
Thanks @sohamkamani

**Comment by rShetty** [comment]
Fixes in #16
