### ISSUE TITLE
Support for Asynchronous HTTP Client

### ISSUE THREAD

**Issue by rShetty** [gojektech/heimdall#18]
- Should support async http client with various methods already supported for HTTP and Hystrix client.
- Something on these lines: `https://godoc.org/golang.org/x/net/context/ctxhttp`

**Comment by rShetty** [comment]
@devdinu Do you want to pick this up ?

**Comment by dcu** [comment]
would this be an extra layer on top of the existing clients?

**Comment by rShetty** [comment]
Maybe a different client at par with http and hystrix client like async client, does this make sense ? @dcu
