### ISSUE TITLE
Split out interfaces for Retrier vs HTTP Client

### ISSUE THREAD

**Issue by rShetty** [gojektech/heimdall#19]
We have a common big interface for retrier related methods vs those for making http requests.
We could have `Client` interface for HTTP related methods and `Retriable` interface for retrier related methods, segregating the interfaces

**Comment by darshanime** [comment]
(hello, I am learning Go and would like to contribute (please pardon my asking dumb questions!))

Currently we have separate interfaces: `Client` and `Retriable`:

```go
// client.go
type Client interface {
	Get(url string, headers http.Header) (*http.Response, error)
	Post(url string, body io.Reader, headers http.Header) (*http.Response, error)
	Put(url string, body io.Reader, headers http.Header) (*http.Response, error)
	Patch(url string, body io.Reader, headers http.Header) (*http.Response, error)
	Delete(url string, headers http.Header) (*http.Response, error)
	Do(req *http.Request) (*http.Response, error)

	SetRetryCount(count int)
	SetRetrier(retrier Retriable)
}

// retry.go
type Retriable interface {
	NextInterval(retry int) time.Duration
}
```

What does this issue aim to achieve?

On a side note, we could look at merging the `Backoff` and `Retriable` interface. They are both related and this could simplify the `heimdall` API.

```go
type Backoff interface {
	Next(retry int) time.Duration
}
```

**Comment by rShetty** [comment]
@darshanime It is always good to have one method interfaces. These help provide composeability when using these/implementing them.

The point of this issue was that we have `Client` interface which has grown quite a lot and needs splitting. The way we do it still being discussed and debated.

**Comment by rShetty** [comment]
With #33 this might not be required.
