### ISSUE TITLE
Functional Options support

### ISSUE THREAD

**Issue by italolelis** [gojektech/heimdall#31]
Hello,

Thank you a lot for this amazing library, it's really useful and well thought. 
How would you feel about supporting function options? Something like this:

```go
hystrixClient := heimdall.NewHystrixHTTPClient(
	timeout,
	heimdall.WithCommandName("MyCommand"),
	heimdall.WithHystrixTimeout(1100),
	heimdall.WithMaxConcurrentRequests(100),
	heimdall.WithErrorPercentThreshold(25),
	heimdall.WithSleepWindow(10),
	heimdall.WithRequestVolumeThreshold(10),
    heimdall.WithHystrixRetryCount(2),
	heimdall.WithHystrixRetrier(heimdall.NewRetrier(heimdall.NewConstantBackoff(10, 5))),
)
```

Is this something you'd like to see in the lib? If yes I can send a PR with it.

Thanks again!

**Comment by rShetty** [comment]
Hey @italolelis I think it makes sense. Can you go ahead with the PR

**Comment by italolelis** [comment]
Closing this issue as #33 is already merged 🎉
