### ISSUE TITLE
Releasing version 3.0.1

### ISSUE THREAD

**Issue by vthiery** [gojektech/heimdall#37]
See comment in #34

**Comment by rShetty** [comment]
@vthiery Doing this, sorry for not doing this earlier

**Comment by rShetty** [comment]
https://github.com/gojektech/heimdall/releases/tag/v3.0.1, please move to this newer version and let me know if this fixes this issue. Thanks

**Comment by vthiery** [comment]
All good! Thanks!

**Comment by rShetty** [comment]
Closing this. Thanks for pointing out.
