### ISSUE TITLE
Do method private in hystrix client. 

### ISSUE THREAD

**Issue by nawuko** [gojektech/heimdall#4]
Currently the do function is private
https://github.com/gojektech/heimdall/blob/6ce64ecf951195bdff9db6b754d81253a22f4235/hystrix_client.go#L124
This prevents from using heimdall as true http.Client wrapper.

**Comment by sohamkamani** [comment]
https://github.com/gojektech/heimdall/issues/3

**Comment by rShetty** [comment]
This is fixed in #10. Thanks to @sohamkamani
