### ISSUE TITLE
when a POST operation returns >= 500 the retry fails

### ISSUE THREAD

**Issue by dcu** [gojektech/heimdall#42]
apparently it's because the request body is already read and not restored before retrying

here's a possible solution https://medium.com/@xoen/golang-read-from-an-io-readwriter-without-loosing-its-content-2c6911805361

and it's likely happening here:

https://github.com/gojektech/heimdall/blob/master/hystrix/hystrix_client.go#L152

**Comment by rShetty** [comment]
@dcu Yes, this was fixed for httpclient here https://github.com/gojektech/heimdall/commit/6494102a6392a7ba66522eae2f6d791ed9deb23b, can you help fix this for hystrix client ?

**Comment by dcu** [comment]
@rShetty done, please review

I added a few benchmarks and I'm wondering why is the number of allocs so big on `httpclient` when compared with `hystrix` client

**Comment by dcu** [comment]
this is making some of my automated tests fail, I would appreciate it if you could review it soon

thanks in advance

**Comment by rShetty** [comment]
@dcu Was out for a while, will review it today, Thanks
