### ISSUE TITLE
Response Headers

### ISSUE THREAD

**Issue by dimiro1** [gojektech/heimdall#5]
What if I need access to the response headers? Right now the Response [1] struct has no way to get them.

[1] https://github.com/gojektech/heimdall/blob/master/response.go#L4

**Comment by devdinu** [comment]
Since the method returns a custom `heimdall.Response`, headers are lost (we can't access). ideally we could change it to *http.Response if there's no other need for it.

**Comment by rShetty** [comment]
This is fixed in #10 . Thanks to @sohamkamani
