### ISSUE TITLE
while creating new client use time.Duration

### ISSUE THREAD

**Issue by devdinu** [gojektech/heimdall#6]
`func NewHTTPClient(timeoutInMilliseconds int) Client` in [http_client](https://github.com/gojektech/heimdall/blob/master/http_client.go#L24) accepts int but could be `time.Duration`, so its flexible

it could be a `heimdall.Config{...}` so we could add more later.

**Comment by kgrz** [comment]
Why not default to `time.Duration`?. Let the client deal with conversion and passing the correct type.

**Comment by rShetty** [comment]
@kgrz I am not clear on this. What do you have in mind ?

**Comment by kgrz** [comment]
@rShetty Something like this: https://github.com/gojektech/heimdall/compare/master...kgrz:pass-duration-to-client

**Comment by rShetty** [comment]
👍 Agree

**Comment by rShetty** [comment]
@kgrz Wanna raise a PR on this ? I think you already did the required change ?

**Comment by rShetty** [comment]
This is fixed in #13
